### ISSUE TITLE
im stuck at this step

### ISSUE THREAD

**Issue by mrcut** [gberger/proguides-dl#1]
Im getting this error when i Run  : node build-video-list.js > videos.json 

**{ Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }**

**Comment by joesandmeyer** [comment]
I had the same issue. Seems like an easy fix, but the project itself has an easy alternative for now.
If anybody is having issues with this, here is this other method that works as of april '21. Tested on chrome.

right click video review page > inspect > network, then press play on your video
right click the elements to download mp4

**Comment by NAK2021** [comment]
I have a problem when I run "dl-video.js". It said that it could not find the module or sth (MODULE_NOT_FOUND)
